[keyboard]
name = "rmk-planck-split"
product_name = "rmk-planck-split"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "lemon"
chip = "nrf52840"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 4
cols = 12
layers = 4
keymap = [
    [
        ["Escape", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Backspace"],
        ["Tab", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "Enter"],
        ["Capslock", "LCtrl", "LAlt", "LGui", "MO(1)", "Space", "Space", "MO(2)", "Left", "Down", "Up", "Right"]
    ],
]

[behavior]
tri_layer = { upper = 1, lower = 2, adjust = 3 }

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
[split.central.matrix]
input_pins = ["P0_17", "P0_20", "P1_11", "P1_13"]
output_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06" ]

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
input_pins = ["P0_17", "P0_20", "P1_11", "P1_13"]
output_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06" ]
